Design and implement a data warehouse for a retail business, apply ETL (Extraction Transformation, and Load) processes, perform OLAP operations,and generate business
performance reports using Python and MySQL

In [1]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:jenisha@localhost:3306/retail_dss")

query = "SELECT * FROM purchases"
df = pd.read_sql(query, engine)

df.head()

,purchase_id,customer_id,customer_name,product_name,category,quantity,price,purchase_date
0,1,101,john,Laptop,Electronics,1,55000.0,2024-01-10
1,2,102,jacob,Mobile,Electronics,2,30000.0,2024-01-15
2,3,103,bob,Shoes,Fashion,3,4500.0,2024-02-05
3,4,104,mary,T-shirt,Fashion,5,2500.0,2024-02-10
4,5,105,henry,Headphones,Electronics,4,8000.0,2024-03-01

#### TRANSFORM

In [2]:
# Calculate total amount

df['total_amount'] = df['quantity'] * df['price']

In [3]:
# Convert date and extract month & year

df['purchase_date'] = pd.to_datetime(df['purchase_date'])
df['month'] = df['purchase_date'].dt.month_name()
df['year'] = df['purchase_date'].dt.year

In [4]:
print("\nTransformed Data:")
df

Transformed Data:

,purchase_id,customer_id,customer_name,product_name,category,quantity,price,purchase_date,total_amount,month,year
0,1,101,john,Laptop,Electronics,1,55000.0,2024-01-10,55000.0,January,2024
1,2,102,jacob,Mobile,Electronics,2,30000.0,2024-01-15,60000.0,January,2024
2,3,103,bob,Shoes,Fashion,3,4500.0,2024-02-05,13500.0,February,2024
3,4,104,mary,T-shirt,Fashion,5,2500.0,2024-02-10,12500.0,February,2024
4,5,105,henry,Headphones,Electronics,4,8000.0,2024-03-01,32000.0,March,2024
5,6,101,luis,Keyboard,Electronics,2,3000.0,2024-03-15,6000.0,March,2024
6,7,102,martha,Jeans,Fashion,2,4000.0,2024-04-01,8000.0,April,2024

#### LOAD

In [5]:
# Save transformed data into new warehouse table

df.to_sql("sales_warehouse", engine, if_exists="replace", index=False)

print("\nData loaded into sales_warehouse table")

Data loaded into sales_warehouse table

#### OLAP OPERATIONS

In [6]:
# 1. Roll-up (Monthly Sales)

monthly_sales = df.groupby('month')['total_amount'].sum()

print("\nMonthly Sales:")

print(monthly_sales)

Monthly Sales:
month
April         8000.0
February     26000.0
January     115000.0
March        38000.0
Name: total_amount, dtype: float64

In [7]:
# 2. Drill-down (Category-wise Sales)

category_sales = df.groupby('category')['total_amount'].sum()

print("\nCategory Wise Sales:")

print(category_sales)

Category Wise Sales:
category
Electronics    153000.0
Fashion         34000.0
Name: total_amount, dtype: float64

In [8]:
# 3. Slice (Sales for 2025)

sales_2025 = df[df['year'] == 2025]['total_amount'].sum()

print("\nSales in 2025:")

print(sales_2025)

Sales in 2025:
0.0

In [9]:
# 4. Dice (Electronics in March)

dice_sales = df[(df['category'] == 'Electronics') & (df['month'] == 'March')]['total_amount'].sum()

print("\nElectronics Sales in March:")

print(dice_sales)

Electronics Sales in March:
38000.0

#### BUSINESS REPORTS

In [10]:
# Total Sales

total_sales = df['total_amount'].sum()

print("\nTotal Sales:", total_sales)

Total Sales: 187000.0

In [11]:
customer_sales_sorted = (
    df.groupby('customer_id')['total_amount']
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

print(customer_sales_sorted.head())

   customer_id  total_amount
0          102       68000.0
1          101       61000.0
2          105       32000.0
3          103       13500.0
4          104       12500.0

In [12]:
# Top 20% Customers

customer_sales = df.groupby('customer_name')['total_amount'].sum()

customer_sales_sorted = customer_sales.sort_values(ascending=False)

In [13]:
top_20 = int(0.2 * len(customer_sales_sorted))

top_customers = customer_sales_sorted.head(top_20)

In [14]:
print("\nTop 20% Customers:")

print(top_customers)

Top 20% Customers:
customer_name
jacob    60000.0
Name: total_amount, dtype: float64

In [15]:
# Best Selling Product

best_product = df.groupby('product_name')['quantity'].sum().idxmax()

print("\nBest Selling Product:", best_product)

Best Selling Product: T-shirt