In [1]:
%pip install selenium webdriver-manager pandas

Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas in c:\users\jenis\anaconda3\lib\site-packages (2.2.3)
Collecting certifi>=2026.1.4 (from selenium)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting typing_extensions<5.0,>=4.15.0 (from selenium)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\jenis\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\jenis\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (24.3.0)
Requirement already satisfied: sortedcontainers in c:\users\jenis\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\jenis\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.7)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\jenis\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\jenis\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.17.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\jenis\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: requests in c:\users\jenis\anaconda3\lib\site-packages (from webdriver-manager) (2.32.3)
Requirement already satisfied: python-dotenv in c:\users\jenis\anaconda3\lib\site-packages (from webdriver-manager) (1.1.0)
Requirement already satisfied: packaging in c:\users\jenis\anaconda3\lib\site-packages (from webdriver-manager) (24.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jenis\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jenis\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jenis\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jenis\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: pycparser in c:\users\jenis\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\jenis\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\jenis\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jenis\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.3.2)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.5 MB 8.8 MB/s eta 0:00:01
   ------------ --------------------------- 2.9/9.5 MB 8.5 MB/s eta 0:00:01
   --------------- ------------------------ 3.7/9.5 MB 8.7 MB/s eta 0:00:01
   ----------------------- ---------------- 5.5/9.5 MB 7.3 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.5 MB 7.4 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.5 MB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 7.6 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, typing_extensions, outcome, certifi, trio, webdriver-manager, trio-websocket, selenium

  Attempting uninstall: urllib3

    Found existing installation: urllib3 2.3.0

    Uninstalling urllib3-2.3.0:

      Successfully uninstalled urllib3-2.3.0

   ---- ----------------------------------- 1/9 [urllib3]
  Attempting uninstall: typing_extensions
   ---- ----------------------------------- 1/9 [urllib3]
    Found existing installation: typing_extensions 4.12.2
   ---- ----------------------------------- 1/9 [urllib3]
    Uninstalling typing_extensions-4.12.2:
   ---- ----------------------------------- 1/9 [urllib3]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
      Successfully uninstalled typing_extensions-4.12.2
   -------- ------------------------------- 2/9 [typing_extensions]
   -------- ------------------------------- 2/9 [typing_extensions]
  Attempting uninstall: certifi
   -------- ------------------------------- 2/9 [typing_extensions]
    Found existing installation: certifi 2025.4.26
   -------- ------------------------------- 2/9 [typing_extensions]
    Uninstalling certifi-2025.4.26:
   -------- ------------------------------- 2/9 [typing_extensions]
      Successfully uninstalled certifi-2025.4.26
   -------- ------------------------------- 2/9 [typing_extensions]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ------------------------------- -------- 7/9 [trio-websocket]
   ----------------------------------- ---- 8/9 [selenium]
   ----------------------------------- ---- 8/9 [selenium]
   ----------------------------------- ---- 8/9 [selenium]
   ----------------------------------- ---- 8/9 [selenium]
   ----------------------------------- ---- 8/9 [selenium]
   ----------------------------------- ---- 8/9 [selenium]
   ----------------------------------- ---- 8/9 [selenium]
   ---------------------------------------- 9/9 [selenium]

Successfully installed certifi-2026.2.25 outcome-1.3.0.post0 selenium-4.41.0 trio-0.33.0 trio-websocket-0.12.2 typing_extensions-4.15.0 urllib3-2.6.3 webdriver-manager-4.0.2 wsproto-1.3.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

In [3]:
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
driver  = webdriver.Chrome(service = Service(ChromeDriverManager().install()), options=options)

In [4]:
url = "https://www.youtube.com/watch?v=HhesaQXLuRY"
driver.get(url)
time.sleep(5)

In [5]:
driver.execute_script("window.scrollTo(0,800);")
time.sleep(3)

In [6]:
# scroll mulitple times to load more comments
for i in range(10):
    driver.execute_script("window.scrollBy(0,1000);")
    time.sleep(3)

In [7]:
# extract comments
comments = driver.find_elements(By.XPATH, '//*[@id="content-text"]')

In [8]:
comment_list = []
for comment in comments:
    comment_list.append(comment.text)

In [9]:
driver.quit()
df = pd.DataFrame(comment_list, columns=["Comment"])
df.head()

                                             Comment
0  Hank : " Get a little excitement in your life"...
1  If you haven't seen this, you've literally mis...
2  If you haven't seen breaking bad your eyes are...
3  I can't wait for this to come out, Better Call...
4   You know the business and i know the chemistry..

In [10]:
print("Total comments Collected: ", len(df))
df.tail(10)

Total comments Collected:  40

                                              Comment
30                             Jesse we need to cook.
31  Walter White is the most beautiful tv characte...
32  Funny thing is, the trailer looks just ordinar...
33  Most of the people came here after A Shitty En...
34  Hank to Walt in episode 1: "Get a little excit...
35  Hank and Hesingberg relationship is all about ...
36  and that was the start of the greatest TV show...
37  You guys who haven't watched that yet are real...
38         This is not a serie ,this is a masterpiece
39  Can't wait to watch this a week after Better C...

In [11]:
%pip install nltk textblob wordcloud matplotlib

Requirement already satisfied: nltk in c:\users\jenis\anaconda3\lib\site-packages (3.9.1)
Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Collecting wordcloud
  Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: matplotlib in c:\users\jenis\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: click in c:\users\jenis\anaconda3\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\jenis\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jenis\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\jenis\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: numpy>=1.19.3 in c:\users\jenis\anaconda3\lib\site-packages (from wordcloud) (2.1.3)
Requirement already satisfied: pillow in c:\users\jenis\anaconda3\lib\site-packages (from wordcloud) (11.1.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jenis\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\jenis\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: colorama in c:\users\jenis\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 6.4 MB/s eta 0:00:00
Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl (306 kB)
Installing collected packages: wordcloud, textblob

   ---------------------------------------- 2/2 [textblob]

Successfully installed textblob-0.19.0 wordcloud-1.9.6
Note: you may need to restart the kernel to use updated packages.

In [12]:
import nltk
nltk.download('stopwords')
import re
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jenis\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
stop_words = set(stopwords.words("english"))
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

In [14]:
df["Cleaned"] = df["Comment"].apply(clean_text)
df.head(5)

,Comment,Cleaned
0,"Hank : "" Get a little excitement in your life""...",hank get little excitement life worst advice e...
1,"If you haven't seen this, you've literally mis...",havent seen youve literally missed greatest tv...
2,If you haven't seen breaking bad your eyes are...,havent seen breaking bad eyes still virgin
3,"I can't wait for this to come out, Better Call...",cant wait come better call saul masterpiece sh...
4,You know the business and i know the chemistry..,know business know chemistry